---
name: Build
run-name: ${{ inputs.workflow_name }}
on:
  workflow_dispatch:
    inputs:
      startDatetime:
        type: string
        required: true
        description: startDatetime
        default: '2024-03-10T00:00:00Z'
      endDatetime:
        type: string
        required: true
        description: endDatetime
        default: '2024-03-17T00:00:00Z'
      min_lon:
        type: string
        required: true
        description: min_lon
        default: -122.12
      min_lat:
        type: string
        required: true
        description: min_lat
        default: 46.6
      max_lon:
        type: string
        required: true
        description: max_lon
        default: -121.35
      max_lat:
        type: string
        required: true
        description: max_lat
        default: 47.1
      satellite:
        type: choice
        required: true
        description: satellite
        default: goes18
        options:
          - goes16
          - goes17
          - goes18
      product:
        type: choice
        required: true
        description: product
        default: ABI-L1b-RadC
        options:
          - ABI-L1b-RadC
          - ABI-L1b-RadF
      band:
        type: choice
        required: true
        description: band
        default: '7'
        options:
          - '1'
          - '2'
          - '3'
          - '4'
          - '5'
          - '6'
          - '7'
          - '8'
          - '9'
          - '10'
          - '11'
          - '12'
          - '13'
          - '14'
          - '15'
          - '16'
      workflow_name:
        description: Custom workflow name
        required: false
        default: goes-build-zarr
        type: string
  workflow_call:
    inputs:
      startDatetime:
        type: string
        description: startDatetime
      endDatetime:
        type: string
        description: endDatetime
      min_lon:
        type: string
        description: min_lon
      min_lat:
        type: string
        description: min_lat
      max_lon:
        type: string
        description: max_lon
      max_lat:
        type: string
        description: max_lat
      satellite:
        type: string
        description: satellite
      product:
        type: string
        description: product
      band:
        type: string
        description: band
      workflow_name:
        description: Custom workflow name
        type: string
jobs:
  build-zarr:
    name: ${{ inputs.workflow_name }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Add conda to system path
        run: |
          echo $CONDA/bin >> $GITHUB_PATH
      - name: Install mamba and dependencies
        run: >
          conda install mamba -c conda-forge

          mamba env update --file environment.yml --name goesenv

          source $CONDA/etc/profile.d/conda.sh

          conda activate goesenv

          pip install goes_ortho@git+https://github.com/spestana/goes-ortho@re-org

          pip install goespy@git+https://github.com/spestana/goes-py

          pip install gtsa@git+https://github.com/friedrichknuth/gtsa
      - name: Run build-zarr script
        env:
          OPENTOPO_API_KEY: ${{ secrets.OPENTOPO_API_KEY }}
        run: |
          source ~/.bashrc; mamba init; mamba activate goesenv; python -c "\
          import goes_ortho as go; \
          go.get_data.make_request_json('${{ inputs.workflow_name }}', '(${{ inputs.startDatetime }}', '${{ inputs.endDatetime }}', \
          [${{ inputs.min_lon }}, ${{ inputs.min_lat }}, ${{ inputs.max_lon }}, ${{ inputs.max_lat }}], \
          '${{ inputs.satellite }}', '${{ inputs.product }}', ${{ inputs.band }}, '${{ inputs.variable }}', '${{ secrets.OPENTOPO_API_KEY }}')"
